name: Test Docker Builds

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: snapcast-runner
    strategy:
      matrix:
        service: [snapMULTI, mpd]
    steps:
      - uses: actions/checkout@v4

      - name: Build ${{ matrix.service }}
        run: |
          TAG=$(echo "test-${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
          docker build -f Dockerfile.${{ matrix.service }} --tag ${TAG}:latest .

      - name: Test container
        run: |
          TAG=$(echo "test-${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
          docker run --rm ${TAG}:latest sh -c "which snapserver || which mpd"
